runtime: python37

handlers:
- url: /(favicon\.ico|apple-touch-icon\.png|browserconfig\.xml)$
  static_files: static/icons/\1
  upload: static/icons/(favicon\.ico|apple-touch-icon\.png|browserconfig\.xml)$
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
