runtime: python37

handlers:
- url: /(site\.webmanifest|browserconfig\.xml)$
  static_files: static/manifests/\1
  upload: static/manifests/.*
  secure: always

- url: /(favicon\.ico|favicon-\d{2}x\d{2}\.png|android-chrome-\d{3}x\d{3}\.png|apple-touch-icon\.png|mstile-150x150\.png|safari-pinned-tab\.svg|og-image\.jpg)$
  static_files: static/icons/\1
  upload: static/icons/.*
  secure: always

- url: /(sw\.js)$
  static_files: static/js/\1
  upload: static/js/sw\.js
  secure: always

- url: /css
  static_dir: static/css
  secure: always

- url: /fonts
  static_dir: static/fonts
  secure: always

- url: /images
  static_dir: static/images
  secure: always

- url: /js
  static_dir: static/js
  secure: always

# to handle /static/og-image.jpg
- url: /static
  static_dir: static/icons
  secure: always

- url: /.*
  script: auto
  secure: always
